{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default (printf "%s-data" (include "base.fullname" .)) }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  {{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
  {{- end }}
{{- end }}
